### PR TITLE
Add support for italics

### PR DESCRIPTION
**Pull request by kirbyfan64**
I was slightly surprised that this wasn't available yet!

### CODE REVIEW

**Comment by Aetf** [comment]
I was just about to cherry pick italics support from another fork. Planned to do this a while ago but completely forget this...

Thanks for the patch! :+1:

**Comment by GordStephen** [comment]
Apologies for posting this here,  @Aetf's kmscon fork doesn't have issues enabled - how hard would it be to apply this functionality in kmscon? The [underline commit](https://github.com/Aetf/kmscon/commit/7b049cee0cab9235d1954c1c84ceb0554ab5370e) didn't seem too complicated, would this be comparable?

**Comment by kirbyfan64** [comment]
@GordStephen Yeah, it should be pretty much the same.

**Comment by Aetf** [comment]
Oh, I didn't notice I disabled issues for my kmscon fork. Please move the discussion there: Aetf/kmscon#1

**Pull request merged**
